### ISSUE TITLE
Timeout of cbs_roadmap

### ISSUE THREAD

**Issue by ct2034** [whoenig/libMultiRobotPlanning#33]
On this (unsolvable) scenario, the cbs_roadmap planner times out for me (or takes more than 60s)
Note that vertex 4 is disconnected from the rest of the graph:
```
{agents: [{goal: '4', name: agent0, start: '0'}], roadmap: {allow_wait_actions: true,
    edges: [['0', '1'], ['0', '3'], ['0', '2'], ['1', '2'], ['2', '3']], undirected: true,
    vertices: {'0': [0.0, 0.0], '1': [1.0, 0.0], '2': [1.0, 1.0], '3': [0.0, 1.0],
      '4': [2.0, 2.0]}}}
```
and annotated:
```
agents:
- goal: '4'
  name: agent0
  start: '0'
roadmap:
  allow_wait_actions: false
  conflicts:
  - - 1
    - 2
    - 5
    - 8
    - 10
    - 11
  - - 0
    - 2
    - 4
    - 6
    - 10
    - 13
  - - 0
    - 1
    - 3
    - 7
    - 9
    - 10
    - 12
  - - 2
    - 5
    - 8
    - 9
    - 11
    - 12
  - - 1
    - 7
    - 8
    - 9
    - 12
    - 13
  - - 0
    - 3
    - 6
    - 7
    - 10
    - 11
  - - 1
    - 5
    - 7
    - 9
    - 10
    - 13
  - - 2
    - 4
    - 5
    - 6
    - 8
    - 10
    - 12
  - - 0
    - 3
    - 4
    - 7
    - 11
    - 12
  - - 2
    - 3
    - 4
    - 6
    - 12
    - 13
  - - 0
    - 1
    - 2
    - 5
    - 6
    - 7
  - - 0
    - 3
    - 5
    - 8
  - - 2
    - 3
    - 4
    - 7
    - 8
    - 9
  - - 1
    - 4
    - 6
    - 9
  - []
  edges:
  - - '0'
    - '1'
  - - '0'
    - '3'
  - - '0'
    - '2'
  - - '1'
    - '2'
  - - '2'
    - '3'
  - - '1'
    - '0'
  - - '3'
    - '0'
  - - '2'
    - '0'
  - - '2'
    - '1'
  - - '3'
    - '2'
  - - '0'
    - '0'
  - - '1'
    - '1'
  - - '2'
    - '2'
  - - '3'
    - '3'
  - - '4'
    - '4'
  undirected: false
  vertices:
    '0':
    - 0.0
    - 0.0
    '1':
    - 1.0
    - 0.0
    '2':
    - 1.0
    - 1.0
    '3':
    - 0.0
    - 1.0
    '4':
    - 2.0
    - 2.0
```
The configured Radius was `.2`
detected in a0ac3bbd4bdbb09fe74c75032d90252eb147015e
