### ISSUE TITLE
Optimal path in terms of the time reached results in suboptimal path in terms of robot movement costs

### ISSUE THREAD

**Issue by ProVival** [whoenig/libMultiRobotPlanning#52]
Hi, thanks for your work! This was the most easy to understand repository for me to get into multi agent path finding so really thanks a lot :D 

I was trying random start and goal locations for agents to test the limitations and drawbacks and i came across to a case where agents are finding the optimal path in terms of time but robots are moving excessively. In the case below:
```
agents:
  - goal: [13, 7]
    name: agent0
    start: [12, 7]
  - goal: [13, 8]
    name: agent1
    start: [13, 3]
  - goal: [13, 9]
    name: agent2
    start: [13, 4]
  - goal: [13, 10]
    name: agent3
    start: [13, 5]
map:
  dimensions: [21, 14]
  obstacles:
    - [12, 13]
    - [14, 13]
    - [12, 12]
    - [14, 12]
```

agent0 moves to `13,7` from `12,7` in the beginning and then it moves back to `12,7` because other agents are passing through `13,7` at timesteps 2,3,4. But instead of doing this agent0 could've wait at `12,7` until timestep 4 and then move to  `13,7`at timestep 5 that would be more optimal for robots because it does not move unnecessarily. I tried to change the cost for waiting action but  that results in way too expensive search processes. Also thought about changing the comparison function for focalSet since `State(1,12,7) `is in the focalSet it is just not expanded. But i couldn't find a way to tweak it in a way that does not cause the algorithm to spend too much time on unnecessary states.

Is it somehow possible to make the agents prioritize the movement costs and the timestep at the sametime? I am cracking my head on this to no avail so i wanted to know if you have an idea about how to modify it, thanks again!

Note: I tried to add costs for changing direction and that prevents this from happening most of the time but it gives me bad access exception or segmentation fault sometimes so i don't know how should i go with that
